Repository vbence86/fivenations, pull requests merged in 2018-06, with the labels that each got.

#542 Add new map to gameplay
  src/assets/datas/common/weapons.json
  src/assets/datas/units/fed/orca.json
  src/assets/datas/units/tho/maraduer.json
  src/assets/datas/units/tho/predator.json
  src/assets/maps/thorun_test.json
  src/js/gui/GUI.js
  src/js/preloader/Maps.js
  src/web/index.html
Labels: Easy Shuttle

#575 Fixes for 547, 548
  src/js/entities/Entity.js
  src/js/entities/production/ProductionManager.js
  src/js/sync/Entity.Cancel.Production.js
Labels: Fearful Flagship

#577 #576 entity.getClosestAllyEntitiesInRange always returns an array
  src/js/entities/Entity.js
Labels: Fearful Flagship

#578 #558 Projectile gets removed if out of range
  src/assets/datas/projectiles/cannonball.json
  src/assets/datas/projectiles/kinetic-torpedo.json
  src/assets/datas/projectiles/lancet-gun.json
  src/assets/datas/projectiles/laser-beam-1.json
  src/assets/datas/projectiles/proton-torpedo.json
  src/assets/datas/projectiles/q-disruptor.json
  src/assets/datas/projectiles/ragnarok-heavy-gun.json
  src/assets/datas/projectiles/rommel.json
  src/assets/datas/projectiles/thermobaric-bomb.json
  src/js/effects/Effect.js
  src/js/effects/EffectManager.js
  src/js/entities/weapons/Weapon.js
  src/js/model/DataObject.js
Labels: Fearful Flagship

#580 #567 minimap colour can be customized
  src/assets/datas/units/ast/asteroid1.json
  src/assets/datas/units/ast/asteroid2.json
  src/assets/datas/units/ast/asteroid3.json
  src/assets/datas/units/ast/asteroid4.json
  src/assets/datas/units/ast/asteroid_silicon_sm02.json
  src/assets/datas/units/ast/asteroid_silicon_sm02.png
  src/assets/datas/units/ast/asteroidbig1.json
  src/assets/datas/units/ast/asteroidbig2.json
  src/assets/datas/units/ast/asteroidice1.json
  src/assets/datas/units/ast/asteroidice2.json
  src/assets/datas/units/ast/asteroidicesmall1.json
  src/assets/datas/units/ast/asteroidicesmall2.json
  src/assets/datas/units/ast/asteroidsilicon1.json
  src/assets/datas/units/ast/asteroidsilicon2.json
  src/assets/datas/units/ast/asteroidsiliconsmall1.json
  src/assets/datas/units/ast/asteroidsiliconsmall2.json
  src/assets/datas/units/ast/asteroidsmall1.json
  src/assets/datas/units/ast/asteroidsmall2.json
  src/assets/datas/units/ast/asteroidsmall3.json
  src/assets/datas/units/ast/asteroidsmall4.json
  src/assets/datas/units/ast/asteroidtitanium1.json
  src/assets/datas/units/ast/asteroidtitanium2.json
  src/assets/datas/units/ast/asteroidtitaniumsmall1.json
  src/assets/datas/units/ast/asteroidtitaniumsmall2.json
  src/assets/datas/units/ast/asteroiduranium1.json
  src/assets/datas/units/ast/asteroiduranium2.json
  src/assets/datas/units/ast/asteroiduraniumsmall1.json
  src/assets/datas/units/ast/asteroiduraniumsmall2.json
  src/js/gui/Minimap.js
  src/js/model/DataObject.js
Labels: Fearful Flagship

#581 #568 refactor minimap rendering
  src/js/gui/GUI.js
  src/js/gui/Minimap.js
  src/js/map/FogOfWar.js
Labels: Fearful Flagship

#584 #557 Extend multiselection functionality with negative selection
  src/js/gui/UserPointer.js
Labels: Fearful Flagship

#588 Feature/574
  src/js/common/Const.js
  src/js/gui/CancelPage.js
  src/js/gui/ControlPage.js
  src/js/gui/ControlPanel.js
  src/js/gui/EntityDetailsDisplay.js
  src/js/gui/GUI.js
  src/js/gui/Minimap.js
  src/js/gui/Panel.js
  src/js/gui/ProductionTab.js
  src/js/gui/ResourceDisplay.js
  src/js/gui/UserPointer.js
  src/js/preloader/GUI.js
  src/js/scenes/Game.js
  src/js/starfield/Background.js
  src/web/index.html
Labels: Fearful Flagship

#596 Feature/560
  src/js/entities/Entity.js
  src/js/entities/activities/shared/Attack.js
  src/js/sync/Entity.Attack.js
  src/js/sync/Entity.Dock.js
  src/js/sync/EventEmitter.js
Labels: Fearful Flagship

#600 #550 decrease supply of civilbase
  src/assets/datas/units/fed/civilianbase.json
Labels: Fearful Flagship

#601 Feature/300
  src/assets/datas/common/weapons.json
  src/js/entities/Entity.js
  src/js/entities/weapons/Weapon.js
  src/js/sync/Entity.Damage.js
  src/js/sync/EventEmitter.js
Labels: Fearful Flagship

#603 Feature/469
  src/js/common/CollisionManager.js
  src/js/effects/Effect.js
  src/js/effects/EffectManager.js
  src/js/entities/Entity.js
  src/js/entities/weapons/Weapon.js
  src/js/entities/weapons/WeaponManager.js
  src/js/gui/AttackButton.js
  src/js/sync/Entity.Attack.js
  src/js/sync/Entity.Damage.js
  src/js/sync/EventEmitter.js
Labels: Fearful Flagship

#604 #556 fix atlas files of asteroids
  src/assets/images/units/ast/asteroid01.json
  src/assets/images/units/ast/asteroid02.json
  src/assets/images/units/ast/asteroid03.json
  src/assets/images/units/ast/asteroid04.json
  src/assets/images/units/ast/asteroid_big01.json
  src/assets/images/units/ast/asteroid_big02.json
  src/assets/images/units/ast/asteroid_ice01.json
  src/assets/images/units/ast/asteroid_ice02.json
  src/assets/images/units/ast/asteroid_ice_sm01.json
  src/assets/images/units/ast/asteroid_ice_sm02.json
  src/assets/images/units/ast/asteroid_silicon01.json
  src/assets/images/units/ast/asteroid_silicon02.json
  src/assets/images/units/ast/asteroid_silicon_sm01.json
  src/assets/images/units/ast/asteroid_silicon_sm02.json
  src/assets/images/units/ast/asteroid_sm01.json
  src/assets/images/units/ast/asteroid_sm02.json
  src/assets/images/units/ast/asteroid_sm03.json
  src/assets/images/units/ast/asteroid_sm04.json
Labels: Fearful Flagship

#606 #571 Add counter animation to ResourceDisplay update
  src/js/gui/ResourceDisplay.js
Labels: Fearful Flagship

#612 #561 make killing the Move Activity toggleable
  src/js/entities/activities/shared/GetInRange.js
  src/js/entities/activities/shared/GetToDock.js
  src/js/entities/activities/shared/Move.js
Labels: Fearful Flagship

#618 #583 add guard around Entity.Cargo.Alter event body
  src/js/sync/Entity.Cargo.Alter.js
Labels: Fearful Flagship

#619 #562 set JetEngine off when the entity is force stopped
  src/js/entities/misc/JetEngine.js
  src/js/entities/motions/MotionManager.js
Labels: Fearful Flagship

#620 #616 remove entities inside Carriers
  src/js/entities/EntityManager.js
Labels: Fearful Flagship

#621 Feature/614
  package.json
  src/js/entities/Entity.js
  src/js/gui/HangarDisplay.js
  src/js/gui/HangarDisplaySlot.js
  src/js/gui/StatusDisplay.js
  src/js/sync/Entity.Attack.js
Labels: Fearful Flagship, enhancement

#622 Refactored Sylon entities
  src/assets/images/units/syl/syl_build01.json
  src/assets/images/units/syl/syl_build01.png
  src/assets/images/units/syl/syl_build02.json
  src/assets/images/units/syl/syl_build02.png
  src/assets/images/units/syl/syl_build03.json
  src/assets/images/units/syl/syl_build03.png
  src/assets/images/units/syl/syl_build04.json
  src/assets/images/units/syl/syl_build04.png
  src/assets/images/units/syl/syl_build05.json
  src/assets/images/units/syl/syl_build05.png
  src/assets/images/units/syl/syl_build06.json
  src/assets/images/units/syl/syl_build06.png
  src/assets/images/units/syl/syl_build07.json
  src/assets/images/units/syl/syl_build07.png
  src/assets/images/units/syl/syl_build08.json
  src/assets/images/units/syl/syl_build08.png
  src/assets/images/units/syl/syl_build09.json
  src/assets/images/units/syl/syl_build09.png
  src/assets/images/units/syl/syl_build10.json
  src/assets/images/units/syl/syl_build10.png
  src/assets/images/units/syl/syl_build11.json
  src/assets/images/units/syl/syl_build11.png
  src/assets/images/units/syl/syl_build12.json
  src/assets/images/units/syl/syl_build12.png
  src/assets/images/units/syl/syl_build13.json
  src/assets/images/units/syl/syl_build13.png
  src/assets/images/units/syl/syl_build14.json
  src/assets/images/units/syl/syl_build14.png
  src/assets/images/units/syl/syl_build_buildingphases.json
  src/assets/images/units/syl/syl_build_buildingphases.png
  src/assets/images/units/syl/syl_unit01.json
  src/assets/images/units/syl/syl_unit01.png
  src/assets/images/units/syl/syl_unit02.json
  src/assets/images/units/syl/syl_unit02.png
  src/assets/images/units/syl/syl_unit03.json
  src/assets/images/units/syl/syl_unit03.png
  src/assets/images/units/syl/syl_unit04.json
  src/assets/images/units/syl/syl_unit04.png
  src/assets/images/units/syl/syl_unit05.json
  src/assets/images/units/syl/syl_unit05.png
  src/assets/images/units/syl/syl_unit06.json
  src/assets/images/units/syl/syl_unit06.png
  src/assets/images/units/syl/syl_unit07.json
  src/assets/images/units/syl/syl_unit07.png
  src/assets/images/units/syl/syl_unit08.json
  src/assets/images/units/syl/syl_unit08.png
  src/assets/images/units/syl/syl_unit09.json
  src/assets/images/units/syl/syl_unit09.png
  src/assets/images/units/syl/syl_unit10.json
  src/assets/images/units/syl/syl_unit10.png
  src/assets/images/units/syl/syl_unit11.json
  src/assets/images/units/syl/syl_unit11.png
  src/assets/images/units/syl/syl_unit12.json
  src/assets/images/units/syl/syl_unit12.png
  src/assets/images/units/syl/syl_unit13.json
  src/assets/images/units/syl/syl_unit13.png
  src/assets/images/units/syl/syl_unit14.json
  src/assets/images/units/syl/syl_unit14.png
  src/assets/images/units/syl/syl_unitandbuilding_wreckages.json
  src/assets/images/units/syl/syl_unitandbuilding_wreckages.png
Labels: Art, Fearful Flagship, enhancement

#623 Feature/554
  src/js/entities/Entity.js
  src/js/entities/activities/shared/Attack.js
  src/js/entities/motions/Effects.js
  src/js/entities/motions/MotionManager.js
  src/js/map/CollisionMap.js
Labels: Fearful Flagship

#625 #608 Make game stage responsive
  src/js/scenes/Boot.js
  src/web/index.html
Labels: Fearful Flagship

#626 Feature/565
  src/assets/datas/units/ast/asteroidgigantic1.json
  src/assets/datas/units/ast/asteroidgigantic10.json
  src/assets/datas/units/ast/asteroidgigantic2.json
  src/assets/datas/units/ast/asteroidgigantic3.json
  src/assets/datas/units/ast/asteroidgigantic4.json
  src/assets/datas/units/ast/asteroidgigantic5.json
  src/assets/datas/units/ast/asteroidgigantic6.json
  src/assets/datas/units/ast/asteroidgigantic7.json
  src/assets/datas/units/ast/asteroidgigantic8.json
  src/assets/datas/units/ast/asteroidgigantic9.json
  src/assets/datas/units/ast/asteroidswarm1.json
  src/assets/datas/units/ast/asteroidswarm2.json
  src/assets/datas/units/ast/asteroidswarm3.json
  src/assets/datas/units/ast/asteroidswarm4.json
  src/assets/datas/units/ast/asteroidswarm5.json
  src/assets/datas/units/ast/asteroidswarm6.json
  src/assets/datas/units/ast/asteroidswarm7.json
  src/assets/datas/units/ast/asteroidswarm8.json
  src/js/common/Const.js
  src/js/entities/Entity.js
  src/js/model/DataObject.js
  src/js/preloader/Entities.js
Labels: Fearful Flagship

#628 Feature/549
  src/assets/datas/units/ast/asteroidsilicon1.json
  src/assets/datas/units/ast/asteroidsilicon2.json
  src/assets/datas/units/ast/asteroidtitanium1.json
  src/assets/datas/units/ast/asteroidtitanium2.json
  src/assets/datas/units/ast/asteroiduranium1.json
  src/assets/datas/units/ast/asteroiduranium2.json
  src/js/common/CallbackCollection.js
  src/js/common/CallbackPool.js
  src/js/entities/Entity.js
  src/js/entities/callbacks/checkAsteroidHull.js
  src/js/entities/motions/MotionManager.js
Labels: Fearful Flagship

#629 Feature/553
  src/js/entities/Entity.js
  src/js/gui/UserKeyboard.js
  src/js/gui/controlgroups/ControlGroup.js
  src/js/gui/controlgroups/ControlGroupManager.js
  src/js/scenes/Game.js
Labels: Fearful Flagship
